---
language: java
services:
  - docker
jdk:
  - openjdk11
branches:
  only:
    - master
    - development
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"

 #before_deploy: bash docker_push

before_script:
  - chmod +x gradlew

before_install:
  - chmod +x gradlew
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: xBS2UYLObZVcGS2ohzV9YeBN1VwV3jdky63hEor2IA4QFMWJ1J+bwdkt6ve/XO6gpQRAA3v1UFGpU+rg7yu6+aPnrvfWTaaHZQlMD5s159qEfcJC2OkHmdB5Kq4Umr8g2OfJvZwuerW9SWMJynJxmwvCfOJxrk4idlpkKwfnm7rCEIBPO+qQBDKwlJ9U3KZIU9EMD97zkKndmMLMT8u/K6Scq5UySkz+nOI+6Rj9wYH8plDtbxxhN0EhreOSDW61Gao2VV8PIge6isZ22SPv82ZW/CwHhQSgfUhr0YvCdHS35W0nozKoyh68Oh7ZmLCINKFvZ3sysqqSzzBdgv8k7EeV7lCktnT6Bb7ib9RmblpqFrNkLdLGJH+/OSNXgYzUMungqUoxPmkL5/jHTDbBvPZ3NSoqiXDIDwnIOB1v5ZV9HwRLUOzwM3crj0JCKPUze7QOVNrkNma0cvbEbNLPvW+7l4eaiPNOE8gsoeAwNPZc+qNnCiob4kpb/dB/EpbBu8XxrXvNPC0+aOwtJXouycbjefRCGYyH97F3CZXkdSdlAb+lYUqDpJcFtINadIJSZmW/39nmJ9XIbivH7Y4M4h5SEebaYP11xampKawPynTXJssTPcfA1+3zGq6fEJ+INbCsmQycXa0TFb7hxf7JVVEgdbywaMxbkwvsnryQOkw=
  secret_access_key:
    secure: fK3lMSjOkx/4qX3H8mcSkJ3vyAkQTJvtbp7KYzu0VQE7BbwqLBJgLZWuXnVBJAeGjVYujXPCGkj+dqQ/nBT1fOt55TnEPc51w6vl7b8dxG3nQv4X7taXTEZnGCbztrXt979l4Knjam389HNqhoXRmfGKJdWhVHf6HgKls6c/icVJVfSz9dO11CTPxT83zeWanUXZYQ6FGcOB+comR1yEnjtXnBQngD/zjgNzIboE/EetvrPNDOlV4H/gTYlq3GOLVdiwJgcrgjmnx/IG7f4C9Rqzc392M+7ZY1MYvan104Sjzt30V2h3s/Ezt+tFzD+k20bSF547Vp6Fu7GwadrWQ3gwqWh0WOx0NkjnX/1c59CCyaR4YAqbLJoDvifVuHTyglFRHhKN7+ZltLcFpC3mmk0kwwXYmDCOnYqwmumTaofFN3sp0BdmQ7GM6w6RVLWx9zGKyEWMUGrCwBKeOyzZqAtZoeEWjk+wGB5Mf6NAjaWRsFM9oBmVGajw3mKG/UoKCVf8DE8xKSxJfnvPh07hhW/gr6ilBpvKQJfPKClxpV5h4HSLpEigorGV+TOCw/1NyPK5Z5NAI+3f2Wd/Wvxq2b066hSexuQKe7Sa7V3RykPwA0EIx5DwkwULjcXSgO/PMcUeDLuQrp1ifk81ENpHA7Oi1SGcnGPgdYpNMyPSryk=
  region: "ap-northeast-2"
  app: "seller-server"
  env: "Ticket-seller"
  bucket_name: "ticket-mrfourfour-bucket"
  on:
    repo: mrfourfour/seller-server
    branch: master
