package com.ticket.seller.repository;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.ticket.seller.AmazoneDynamoDbConfig;
import com.ticket.seller.config.dynamoDbConfig;
import com.ticket.seller.objectMapper.ProductMapper;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.reactive.AutoConfigureWebTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import software.amazon.awssdk.services.dynamodb.DynamoDbAsyncClient;

@RunWith(SpringRunner.class)
@AutoConfigureWebTestClient
@SpringBootTest
public class ProductRepositoryTests {
    @Autowired
    private DynamoDbAsyncClient client;
    @Autowired
    private ProductMapper productMapper;


}
